# frozen_string_literal: true

# Conventional Commits linter for the Ruby monorepo.
#
# Implements the rules of @commitlint/config-conventional with a fixed set of
# per-package scopes (mirroring the JS sibling's @commitlint/config-workspace-scopes).
# Pure Ruby, no external dependencies, so it runs the same way in a git commit-msg
# hook and in CI.
#
# See https://www.conventionalcommits.org.
module CommitLint
  # Conventional Commit types (Angular preset used by config-conventional).
  TYPES = %w[build chore ci docs feat fix perf refactor revert style test].freeze

  # Allowed values for the optional (scope). The scope may also be omitted entirely.
  # A few names intentionally differ from the gem name (see the comment beside each).
  SCOPES = %w[
    utils
    cnpj-dv
    cnpj-fmt
    cnpj-gen
    cnpj-val
    cnpj-utils
    cpf-dv
    cpf-fmt
    cpf-gen
    cpf-val
    cpf-utils
    br-utils
  ].freeze

  HEADER_MAX_LENGTH = 100

  # type(scope)?!?: subject  — scope and the breaking-change "!" are optional.
  HEADER = /\A(?<type>\w+)(?:\((?<scope>[^)]*)\))?(?<bang>!)?: (?<subject>.+)\z/

  # Headers generated by tooling; skipped like config-conventional's defaults.
  IGNORED = [
    /\AMerge /,
    /\ARevert /,
    /\A(?:fixup|squash)! /,
    /\AInitial commit\z/
  ].freeze

  module_function

  # Allowed values for the optional (scope).
  def allowed_scopes
    SCOPES
  end

  # Lint a full commit message; returns an array of error strings (empty == ok).
  def lint(message)
    lines = message.to_s.lines
    header = lines.first.to_s.chomp
    return [] if header.strip.empty? || ignored?(header)

    header_errors(header) + body_errors(lines)
  end

  def ignored?(header)
    IGNORED.any? { |re| re.match?(header) }
  end

  def header_errors(header)
    errors = []
    if header.length > HEADER_MAX_LENGTH
      errors << "header must not exceed #{HEADER_MAX_LENGTH} characters (got #{header.length})"
    end

    match = HEADER.match(header)
    return errors << 'header must match "type(scope): subject" (Conventional Commits)' unless match

    errors + type_errors(match[:type]) + scope_errors(match[:scope]) + subject_errors(match[:subject])
  end

  def type_errors(type)
    errors = []
    errors << "type must be lower-case (got #{type.inspect})" unless type == type.downcase
    errors << "type must be one of: #{TYPES.join(', ')} (got #{type.inspect})" unless TYPES.include?(type.downcase)
    errors
  end

  def scope_errors(scope)
    return [] if scope.nil? || scope.empty?

    errors = []
    errors << "scope must be lower-case (got #{scope.inspect})" unless scope == scope.downcase
    return errors if allowed_scope?(scope)

    errors << "scope #{scope.inspect} is not allowed; use one of: #{allowed_scopes.join(', ')}"
    errors
  end

  def allowed_scope?(scope)
    allowed_scopes.include?(scope.downcase)
  end

  def subject_errors(subject)
    errors = []
    errors << 'subject must not be empty' if subject.strip.empty?
    errors << 'subject must not end with a period' if subject.end_with?('.')
    errors << 'subject must not start with an upper-case letter' if subject.match?(/\A[A-Z]/)
    errors
  end

  def body_errors(lines)
    return [] if lines.length < 2
    return [] if lines[1].chomp.empty?

    ['leave a blank line between the header and the body']
  end
end
